/*Moisés Waidemannm rm563719*/
DROP TABLE T_SLV_CATEGORIA CASCADE CONSTRAINT;
DROP TABLE T_SLV_AUTOR CASCADE CONSTRAINT;
DROP TABLE T_SLV_LIVRO CASCADE CONSTRAINT;
DROP TABLE T_SLV_AUTOR_LIVRO CASCADE CONSTRAINT;
DROP SEQUENCE SEQ_SLV_CATEGORIA;
DROP SEQUENCE SEQ_SLV_AUTOR;
DROP SEQUENCE SEQ_SLV_LIVRO;