/*Moisés Waidemannm rm563719*/
--Tabela Categoria
CREATE TABLE T_SLV_CATEGORIA (
    CD_CATEGORIA NUMBER(3),
    DS_SIGLA_CATEGORIA CHAR(3),
    DS_CATEGORIA VARCHAR2(30)
);

--Comentando as colunas da tabala
COMMENT ON COLUMN T_SLV_CATEGORIA.CD_CATEGORIA IS 'Esse atributo irá receber a chave primária da CATEGORIA. Esse número é sequencia e gerado automaticamente pelo sistema. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN T_SLV_CATEGORIA.DS_SIGLA_CATEGORIA IS 'Contém uma sigla curta, essa coluna fornece uma descrição mais compreensível e amigável para os usuários. Seu conteúdo é obrigatório. ';
COMMENT ON COLUMN T_SLV_CATEGORIA.DS_CATEGORIA IS 'serve para armazenar uma descrição detalhada da categoria. Seu conteúdo é obrigatório.';

--Adicionando NOT NULL as colunas obrigatórias
ALTER TABLE T_SLV_CATEGORIA MODIFY CD_CATEGORIA NUMBER(3) NOT NULL;
ALTER TABLE T_SLV_CATEGORIA MODIFY DS_SIGLA_CATEGORIA CHAR(3) NOT NULL;
ALTER TABLE T_SLV_CATEGORIA MODIFY DS_CATEGORIA VARCHAR2(30) NOT NULL;

--Adicionando as Constraints
ALTER TABLE T_SLV_CATEGORIA 
    ADD CONSTRAINT PK_T_SLV_CATEGORIA PRIMARY KEY (CD_CATEGORIA);
    
ALTER TABLE T_SLV_CATEGORIA
    ADD CONSTRAINT UN_SLV_CATEGORIA_SIGLA UNIQUE (DS_SIGLA_CATEGORIA);
    
ALTER TABLE T_SLV_CATEGORIA
    ADD CONSTRAINT UN_SLV_CATEGORIA_DESC UNIQUE (DS_CATEGORIA);
    
--Criando as sequences da tabela (para gerar um numero aleatório para o CD_CATEGORIA)
CREATE SEQUENCE SEQ_SLV_CATEGORIA
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
;

--Alterando nome da coluna e do unique
ALTER TABLE T_SLV_CATEGORIA RENAME COLUMN DS_SIGLA_CATEGORIA TO DS_SILGA_CATEG;

DESC T_SLV_CATEGORIA;

ALTER TABLE T_SLV_CATEGORIA RENAME CONSTRAINT UN_SLV_CATEGORIA_DESC TO UK_SLV_CATEGORIA_DS_CATEG;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_SLV_CATEGORIA';

ALTER TABLE T_SLV_CATEGORIA DROP CONSTRAINT UK_SLV_CATEGORIA_DS_CATEG;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_SLV_CATEGORIA';


---Tabela Autor
CREATE TABLE T_SLV_AUTOR(
    CD_AUTOR NUMBER(3),
    NM_PRIMEIRO_AUTOR VARCHAR2(20),
    NM_SEGUNDO_AUTOR VARCHAR2(40) 
);

--Comentando as colunas da tabala
COMMENT ON COLUMN T_SLV_AUTOR.CD_AUTOR IS 'Esse atributo irá receber a chave primária do AUTOR. Esse número é sequencia e gerado automaticamente pelo sistema. Seu conteúdo é obrigatório.';
COMMENT ON COLUMN T_SLV_AUTOR.NM_PRIMEIRO_AUTOR IS 'Esse atributo recebe o primerio nome do autor. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_AUTOR.NM_SEGUNDO_AUTOR IS 'Esse atributo recebe o segundo nome do autor. Seu conteúdo é obrigatório';

--Adicionando NOT NULL as colunas obrigatórias
ALTER TABLE T_SLV_AUTOR MODIFY CD_AUTOR NUMBER(3) NOT NULL;
ALTER TABLE T_SLV_AUTOR MODIFY MNM_PRIMEIRO_AUTOR VARCHAR2(20) NOT NULL;
ALTER TABLE T_SLV_AUTOR MODIFY MNM_SEGUNDO_AUTOR VARCHAR2(40)  NOT NULL;

--Adicionando as Constraints
ALTER TABLE T_SLV_AUTOR 
    ADD CONSTRAINT PK_T_SLV_AUTOR PRIMARY KEY (CD_AUTOR);

--Criando as sequences da tabela (para gerar um numero aleatório para o CD_AUTOR)
CREATE SEQUENCE SEQ_SLV_AUTOR
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
;

--Alterando a quantidade de caracteres e adicionando colunas 
ALTER TABLE T_SLV_AUTOR MODIFY NM_SEGUNDO_AUTOR VARCHAR2(90);
DESC T_SLV_AUTOR;

ALTER TABLE T_SLV_AUTOR ADD DS_EMAIL VARCHAR2(40) NOT NULL;
DESC T_SLV_AUTOR;

ALTER TABLE T_SLV_AUTOR MODIFY DS_EMAIL VARCHAR2(40);
DESC T_SLV_AUTOR;

ALTER TABLE T_SLV_AUTOR ADD NM_PAIS_ORIGEM VARCHAR2(30);
DESC T_SLV_AUTOR;

--Tabela Livro
CREATE TABLE T_SLV_LIVRO(
    NR_ISBN NUMBER(8),
    CD_CATEGORIA NUMBER(3),
    NM_TITULO VARCHAR2(50),
    DS_SINOPSE VARCHAR2(200),
    NR_EDICAO NUMBER(2),
    NR_ANO NUMBER(4) 
);

--Comentando as colunas da tabala
COMMENT ON COLUMN T_SLV_LIVRO.NR_ISBN IS 'Esse atributo é a chave primária da entidade, identificação numérico usado mundialmente para catalogar e rastrear livros e outras publicações. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_LIVRO.CD_CATEGORIA IS 'Esse atributo recebe o código recebe a foreign key (CD_CATEGORIA). Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_LIVRO.NM_TITULO IS 'Esse atributo recebe o nome do titulo do livro. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_LIVRO.DS_SINOPSE IS 'Esse atributo recebe a sinopse do livro. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_LIVRO.NR_EDICAO IS 'Esse atributo recebe o número editorial. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_LIVRO.NR_ANO IS 'Esse atributo recebe o ano de laçamento do livro. Seu conteúdo é obrigatório';

--Adicionando NOT NULL as colunas obrigatórias
ALTER TABLE T_SLV_LIVRO MODIFY  NR_ISBN NUMBER(8) NOT NULL;
ALTER TABLE T_SLV_LIVRO MODIFY CD_CATEGORIA NUMBER(3) NOT NULL;
ALTER TABLE T_SLV_LIVRO MODIFY NM_TITULO VARCHAR2(50) NOT NULL;
ALTER TABLE T_SLV_LIVRO MODIFY DS_SINOPSE VARCHAR2(200) NOT NULL;
ALTER TABLE T_SLV_LIVRO MODIFY NR_EDICAO NUMBER(2) NOT NULL;
ALTER TABLE T_SLV_LIVRO MODIFY NR_ANO NUMBER(4) NOT NULL;

--Adicionando as Constraints
ALTER TABLE T_SLV_LIVRO 
    ADD CONSTRAINT T_SLV_LIVRO_PK PRIMARY KEY (NR_ISBN);
    
ALTER TABLE T_SLV_LIVRO 
    ADD CONSTRAINT FK_SLV_LIVRO_CATEGORIA FOREIGN KEY (CD_CATEGORIA) REFERENCES  T_SLV_CATEGORIA(CD_CATEGORIA);

ALTER TABLE T_SLV_LIVRO
    ADD 
    CHECK (NR_ANO > 0);

ALTER TABLE T_SLV_LIVRO
    ADD
    CHECK(NR_EDICA0 > 0);


--Criando as sequences da tabela (para gerar um numero aleatório para o NR_ISBN)
CREATE SEQUENCE SEQ_SLV_LIVRO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
;

--Alterando a quantidade de caracteres e excluindo a chave primária
ALTER TABLE T_SLV_LIVRO MODIFY NR_ISBN NUMBER(13);
DESC T_SLV_LIVRO;

ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT UN_SLV_LIVRO_TITULO UNIQUE (NM_TITULO);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_SLV_LIVRO';

ALTER TABLE T_SLV_LIVRO DROP CONSTRAINT T_SLV_LIVRO_PK CASCADE;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_SLV_LIVRO';



--Tabela ligação do Livro com o Autor
CREATE TABLE T_SLV_AUTOR_LIVRO(
    NR_ISBN NUMBER(8),
    CD_AUTOR NUMBER(3),
    ST_AUTOR_PRINCIPAL NUMBER(1) 
);

--Comentando as colunas da tabala
COMMENT ON COLUMN T_SLV_AUTOR_LIVRO.NR_ISBN IS 'Esse atributo forma a chave primária da entidade, que é uma foreign key. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_AUTOR_LIVRO.CD_AUTOR IS 'Esse atributo forma a chave primária da entidade, que é uma foreign key. Seu conteúdo é obrigatório';
COMMENT ON COLUMN T_SLV_AUTOR_LIVRO.ST_AUTOR_PRINCIPAL IS 'Esse atributo armazena o status do autor. Seu conteúdo é obrigatório';

--Adicionando NOT NULL as colunas obrigatórias
ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY NR_ISBN NUMBER(8) NOT NULL;
ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY CD_AUTOR NUMBER(3) NOT NULL;
ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY ST_AUTOR_PRINCIPAL NUMBER(1) NOT NULL;
    
--Adicionando as Constraints
ALTER TABLE T_SLV_AUTOR_LIVRO 
    ADD CONSTRAINT T_SLV_AUTOR_LIVRO_PK PRIMARY KEY (NR_ISBN, CD_AUTOR);
    
ALTER TABLE T_SLV_AUTOR_LIVRO
    ADD CONSTRAINT FK_SLV_AUTOR_LIVRO_AUTOR FOREIGN KEY (CD_AUTOR) REFERENCES T_SLV_AUTOR (CD_AUTOR);

ALTER TABLE T_SLV_AUTOR_LIVRO
    ADD CONSTRAINT FK_SLV_AUTOR_LIVRO_LIVRO FOREIGN KEY (NR_ISBN) REFERENCES T_SLV_LIVRO (NR_ISBN);

ALTER TABLE T_SLV_AUTOR_LIVRO
    ADD
    CHECK(ST_AUTOR_PRINCIPAL IN(1,2));

--Alterando a quantidade de caracteres e exluindo chave estrangeira
ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY NR_ISBN NUMBER(13);
DESC T_SLV_AUTOR_LIVRO;

ALTER TABLE T_SLV_AUTOR_LIVRO DROP CONSTRAINT FK_SLV_AUTOR_LIVRO_AUTOR;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_SLV_AUTOR_LIVRO';
